### PR TITLE
Removed dependency on flurl

### PR DESCRIPTION
**Pull request by ellern**

### CODE REVIEW

**Comment by shawnmclean** [comment]
Hey @ellern, thanks for the changes. The test `Should_Throw_Mandrill_Exception_When_Server_Error` is failing, did it pass for you?

**Comment by ellern** [comment]
My Visual Studio didn't pick up the tests, so didn't try them. I've commented out the simulated timeout test - could not figure out how to simulate that timeout; one way could be just to throw the same exception as HttpClient does.

I will give VS another shot today.

I actually wanted to add this comment to the pull request but forgot, sorry.

**Comment by ellern** [comment]
Please revert this, I did just install a new version nunit and all tests are failing.

**Comment by shawnmclean** [comment]
I looked into it and fixed it. Will push to nuget after some more refactoring. :+1:

**Pull request merged**
