### PR TITLE
Feature/dotnet core migration

### PR DESCRIPTION
**Pull request by shawnmclean**
- [x] Migrate Implementation.
- [ ] Migrate Tests.
- [ ] Appveyor builds netcore
- [ ] Appveyor publishes nuget package on master/release

### CODE REVIEW

**Comment by ctolkien** [comment]
Any more life in this one?

**Comment by shawnmclean** [comment]
I could pick it back up now since the tooling from vs2017 removes alot of manual work.

**Comment by ctolkien** [comment]
I note that master is currently targeting netcoreapp (this should really be netstandard, probably version 1.3) - so should the work be done on that branch and this branch abandoned?

Happy to help out here..

**Comment by shawnmclean** [comment]
@ctolkien yea, I abandoned that branch. Just working from master.

Yes, please submit PRs as you see fit. Thanks :)

**Pull request closed without merging**
